import { makeStyles, Theme } from '@material-ui/core';

export const useTopBlockStyles = makeStyles<Theme>(theme => ({
  pageRoot: {
    width: '100% !important',
    margin: 0,
    minHeight: '90vh',
    display: 'flex',
    flexFlow: 'column nowrap',
    overflow: 'hidden',
    position: 'relative',
    background: `url('/images/tokenAndNftAuction/bg.svg') no-repeat top center / 100% auto`,
  },
  pageContainer: {
    position: 'relative',
    paddingTop: 190,
    width: '100vw !important',
    maxWidth: '1340px !important',
    display: 'flex',
    margin: '0 auto 0',
    flexDirection: 'column',
    flexWrap: 'nowrap',
    justifyContent: 'center',
  },
  title1: {
    fontFamily: `'Sharp Grotesk DB Cyr Medium 22'`,
    fontWeight: 500,
    fontSize: 28,
    color: '#2B51DA',
    textAlign: 'left',
    marginBottom: 16,
    zIndex: 1,
    [theme.breakpoints.down('sm')]: {
      fontSize: 18,
      textAlign: 'center',
    },
  },
  title2: {
    fontFamily: `'Sharp Grotesk DB Cyr Medium 22'`,
    fontWeight: 500,
    fontSize: 58,
    lineHeight: '75px',
    color: '#171717',
    textAlign: 'left',
    marginBottom: 16,
    zIndex: 1,
    [theme.breakpoints.down('sm')]: {
      fontSize: 32,
      lineHeight: '41.6px',
      marginBottom: 0,
      textAlign: 'center',
    },
  },
  text: {
    fontFamily: `'Inter'`,
    fontWeight: 400,
    fontSize: 20,
    lineHeight: '32px',
    color: '#171717',
    textAlign: 'left',
    maxWidth: 970,
    margin: '40px 0 32px',
    zIndex: 1,
    [theme.breakpoints.down('sm')]: {
      margin: '24px 0 48px',
      lineHeight: '22.5px',
      fontSize: 15,
      width: '90%',
      textAlign: 'center',
    },
  },
  btnBox: {
    display: 'flex',
    justifyContent: 'flex-start',
    marginBottom: 183,
    zIndex: 1,
    [theme.breakpoints.down('sm')]: {
      justifyContent: 'center',
      marginBottom: 0,
    },
  },
  rightImgBox: {
    position: 'relative',
    width: '100%',
    paddingTop: '80px',
  },
  p1: {
    width: '100%',
    maxWidth: '441px',
  },
  bannerImg: {
    display: 'block',
    width: '100%',
  },
  text2: {
    fontFamily: `'Sharp Grotesk DB Cyr Medium 22'`,
    fontWeight: 500,
    fontSize: 36,
    lineHeight: '47px',
    color: '#171717',
    textAlign: 'left',
    zIndex: 1,
    marginBottom: 40,
  },
  text3: {
    fontFamily: `'Inter'`,
    fontWeight: 400,
    fontSize: 16,
    lineHeight: '24px',
    color: '#000000',
    textAlign: 'left',
    marginBottom: 16,
    zIndex: 1,
  },
  smallStart: {
    position: 'absolute',
    right: 60,
    bottom: 100,
    width: 30,
    height: 36,
    animation: `$startAnimation 2s linear infinite`,
    [theme.breakpoints.down('md')]: {
      right: 30,
      bottom: 60,
    },
  },
  bigStart: {
    position: 'absolute',
    left: 83,
    top: 143,
    width: 41,
    height: 50,
    animation: `$startAnimation 2s linear infinite`,
    [theme.breakpoints.down('md')]: {
      left: 53,
      top: 83,
    },
  },
  '@keyframes startAnimation': {
    '0%': {
      transform: 'scale(0.88)',
    },
    '50%': {
      transform: 'scale(1)',
    },
    '100%': {
      transform: 'scale(0.88)',
    },
  },
}));
