import { makeStyles, Theme } from '@material-ui/core';

export const useTextContentStyles = makeStyles<Theme>(theme => ({
  root: {
    position: 'relative',
    width: '100%',
    maxWidth: '1110px',
    margin: '0 auto',
    minHeight: '90vh',
    top: 100,
    paddingBottom: 400,
    paddingTop: theme.spacing(15),
  },
  title: {
    width: '100%',
    fontFamily: 'Sharp Grotesk DB Cyr Medium 22',
    fontWeight: 'bold',
    fontSize: '32px',
    lineHeight: '60px',
    fontFeatureSettings: `'pnum' on, 'lnum' on`,
    textAlign: 'center',
    color: '#171717',
    marginBottom: '36px',
  },
  abstract: {
    width: '100%',
    fontFamily: 'Sharp Grotesk DB Cyr Book 20',
    fontWeight: 400,
    fontSize: '16px',
    textAlign: 'center',
    color: '#171717',
    marginBottom: '36px',
    opacity: 0.8,
  },
  subTitle: {
    width: '100%',
    fontFamily: 'Sharp Grotesk DB Cyr Medium 22',
    fontWeight: 'bold',
    fontSize: '16px',
    textAlign: 'left',
    color: '#171717',
    marginBottom: '36px',
    opacity: 0.8,
  },
  normal: {
    fontFamily: 'Sharp Grotesk DB Cyr Book 20',
    fontWeight: 400,
    fontSize: '16px',
    textAlign: 'left',
    color: '#171717',
    marginBottom: '36px',
    opacity: 0.8,
  },
  underLine: {
    fontFamily: 'Sharp Grotesk DB Cyr Book 20',
    fontWeight: 400,
    fontSize: '16px',
    textAlign: 'left',
    color: '#171717',
    opacity: 0.8,
    textDecoration: 'underline',
  },
  maxText: {
    width: '100%',
    marginBottom: '36px',
  },
  blod: {
    fontWeight: 'bold',
  },
  ul: {
    fontFamily: 'Sharp Grotesk DB Cyr Book 20',
    fontWeight: 400,
    fontSize: '16px',
    textAlign: 'left',
    color: '#171717',
    opacity: 0.8,
  },
  li: {
    ontFamily: 'Sharp Grotesk DB Cyr Book 20',
    fontWeight: 400,
    fontSize: '16px',
    textAlign: 'left',
    color: '#171717',
    opacity: 0.8,
    lineHeight: '26px',
    paddingLeft: '20px',
    '&:before': {
      content: `''`,
      display: 'block',
      width: '4px',
      height: '4px',
      boderRadius: '50%',
      background: '#171717',
      position: 'absolute',
      left: '8px',
      top: '10px',
    },
  },
  openLink: {
    cursor: 'pointer',
    fontFamily: 'Sharp Grotesk DB Cyr Book 20',
    fontWeight: 400,
    fontSize: '16px',
    textAlign: 'left',
    color: '#171717',
    opacity: 0.8,
    textDecoration: 'underline',
  },
}));
