import { makeStyles, Theme } from '@material-ui/core';
import { PARALLAX_MARGIN } from 'src/modules/theme/const';

export const useTypesOfActionStyles = makeStyles<Theme>(theme => ({
  root: {
    position: 'relative',
    background: '#2B51DA',
    color: '#fff',
    minHeight: '100vh',
    marginTop: PARALLAX_MARGIN,
    paddingBottom: theme.spacing(10),
    pointerEvents: 'auto',
    '&::before': {
      content: `''`,
      display: 'block',
      position: 'absolute',
      top: -59,
      width: '100%',
      background: '#2B51DA',
      height: 60,
      borderRadius: '28px 28px 0 0',
    },
    [theme.breakpoints.up('md')]: {
      paddingBottom: theme.spacing(23),
      '&::before': {
        borderRadius: '60px 60px 0 0',
      },
    },
  },
  title: {
    fontFamily: `'Sharp Grotesk DB Cyr Medium 22'`,
    fontWeight: 500,
    fontSize: 44,
    textAlign: 'center',
    marginBottom: 80,
    '@media (max-width: 480px)': {
      fontSize: 22,
      marginBottom: 40,
    },
  },
  canvas: {
    background: 'transparent',
    width: '375px',
    height: '375px',
    display: 'block',
    borderRadius: '43px',
    border: '1px solid #ffffff',
  },
  btnItem: {
    display: 'flex',
    flexFlow: 'column nowrap',
    justifyContent: 'center',
    alignItems: 'center',
    padding: '18px 20px',
    background: '#FFFFFF',
    borderRadius: 24,
    cursor: `url('/images/home/typesOfAuction/cursor.png'),auto`,
    width: 230,
    '&:hover': {
      background: '#C5F5FF',
    },
  },
  btnImg: {
    width: 24,
    height: 24,
    marginBottom: 8,
  },
  btnText: {
    fontFamily: `'Inter'`,
    fontWeight: 500,
    fontSize: 14,
    lineHeight: '21px',
    textAlign: 'center',
    color: '#171717',
  },
  animationBlock: {
    width: '100%',
    maxWidth: '1080px',
    margin: '0 auto',
    display: 'flex',
    flexFlow: 'row nowrap',
    justifyContent: 'center',
    alignItems: 'center',
  },
  centerTop: {
    width: '100%',
    display: 'flex',
    flexFlow: 'row nowrap',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  animationBlockLeft: {
    width: 270,
    display: 'flex',
    flexFlow: 'column nowrap',
    justifyContent: 'flex-start',
    alignItems: 'center',
    padding: ' 27px 20px',
    border: `2px solid rgba(255, 255, 255, 0.5)`,
    borderRadius: '20px',
    cursor: `url('/images/home/typesOfAuction/cursor.png'),auto`,
  },
  animationBlockCenter: {
    flex: 1,
    display: 'flex',
    flexFlow: 'column nowrap',
    justifyContent: 'flex-start',
    alignItems: 'center',
    cursor: `url('/images/home/typesOfAuction/cursor.png'),auto`,
  },
  centerBottom: {
    width: 'calc(100% - 40px)',
    margin: '0 auto',
    display: 'flex',
    flexFlow: 'row nowrap',
    justifyContent: 'center',
    alignItems: 'center',
    padding: ' 5px 0',
    border: `2px solid rgba(255, 255, 255, 0.5)`,
    borderRadius: '20px',
    marginTop: '5px',
  },
  animationBlockMobile: {
    width: '100%',
    maxWidth: '1080px',
    margin: '0 auto',
    display: 'flex',
    flexFlow: 'column nowrap',
    justifyContent: 'center',
    alignItems: 'center',
  },
  animationBlockTopMobile: {
    display: 'flex',
    flexFlow: 'row wrap',
    justifyContent: 'space-between',
    width: 'calc(100% - 40px)',
    margin: '0 auto',
    border: `2px solid rgba(255, 255, 255, 0.5)`,
    borderRadius: 20,
    padding: '16px 12px',
    gap: '16px 20px',
  },
  btnItemMobile: {
    display: 'flex',
    flexFlow: 'column nowrap',
    justifyContent: 'center',
    alignItems: 'center',
    background: '#FFFFFF',
    borderRadius: 24,
    cursor: `url('/images/home/typesOfAuction/cursor.png'),auto`,
    width: '100%',
    height: 60,
    '&:active': {
      background: '#C5F5FF',
    },
  },
  btnImgMobile: {
    width: 20,
    height: 20,
    marginBottom: 4,
  },
  btnTextMobile: {
    fontFamily: `'Inter'`,
    fontWeight: 400,
    fontSize: 10,
    lineHeight: '15px',
    textAlign: 'center',
    color: '#171717',
  },
  animationBlockBottomMobile: {
    width: 'calc(100% - 40px)',
    display: 'flex',
    flexFlow: 'column nowrap',
    gap: '20px',
    justifyContent: 'flex-start',
    alignItems: 'center',
    padding: ' 27px 20px',
    border: `2px solid rgba(255, 255, 255, 0.5)`,
    borderRadius: '20px',
    cursor: `url('/images/home/typesOfAuction/cursor.png'),auto`,
  },
}));
