import { makeStyles } from '@material-ui/core';

export const useAuctionContentStyles = makeStyles(theme => ({
  auctionContentSection: {
    position: 'relative',
    width: '100%',
    borderTop: '1px solid rgba(255, 255, 255, 0.1)',
    borderBottom: '1px solid rgba(255, 255, 255, 0.1)',
    '&:before': {
      content: `''`,
      display: 'block',
      position: 'absolute',
      left: '33%',
      top: 0,
      bottom: '0',
      width: '1px',
      background: 'rgba(255, 255, 255, 0.1)',
      zIndex: 0,
    },
    '&:after': {
      content: `''`,
      display: 'block',
      position: 'absolute',
      right: '33%',
      top: 0,
      bottom: '0',
      width: '1px',
      background: 'rgba(255, 255, 255, 0.1)',
      zIndex: 0,
    },
  },
  auctionContent: {
    position: 'relative',
    width: '100%',
    maxWidth: '1100px',
    margin: '0 auto',
    opacity: 0,
    zIndex: 1,
    padding: '120px 0 0',
    overflowX: 'visible',
    [theme.breakpoints.down('sm')]: {
      padding: '80px 0 0',
    },
  },
  auctionContentShow: {
    position: 'relative',
    width: '100%',
    maxWidth: '1100px',
    margin: '0 auto',
    opacity: 1,
  },
  auctionAnimationContent: {
    position: 'relative',
    width: '100%',
    height: '4000px',
    maxWidth: '1100px',
    margin: '0 auto',
    opacity: 1,
    zIndex: 1,
    [theme.breakpoints.down('md')]: {
      height: 'unset',
    },
  },
  auctionAnimationContentShow: {
    position: 'relative',
    width: '100%',
    height: '4000px',
    maxWidth: '1100px',
    margin: '0 auto',
    opacity: 1,
  },
  title: {
    fontFamily: `'Sharp Grotesk DB Cyr Medium 22'`,
    fontWeight: 500,
    fontSize: '44px',
    marginBottom: '48px',
    [theme.breakpoints.down('sm')]: {
      fontSize: '22px',
      lineHeight: '28.6px',
      margin: '0 16px 40px 16px',
    },
  },
  desc: {
    position: 'relative',
    paddingLeft: '24px',
    fontFamily: `'Inter'`,
    fontWeight: 400,
    fontSize: '20px',
    marginBottom: '40px',
    lineHeight: '30px',
    [theme.breakpoints.down('sm')]: {
      fontSize: '15px',
      paddingLeft: '16px',
    },
  },
  leftTopArrow: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: '10px',
    height: '10px',
    [theme.breakpoints.down('sm')]: {
      left: '16px',
    },
  },
  animationBlock: {
    position: 'sticky',
    top: 0,
    width: '2075px',
    height: '748px',
    [theme.breakpoints.down('md')]: {
      left: '16px',
      height: '400px',
    },
  },
}));
