import { makeStyles, Theme } from '@material-ui/core';

export const useFAQStyles = makeStyles<Theme>(theme => ({
  root: {
    position: 'relative',
    backgroundColor: '#232323',
    minHeight: '100vh',
    pointerEvents: 'auto',
    '&::before': {
      content: `''`,
      display: 'block',
      position: 'absolute',
      top: -54,
      width: '100%',
      background: '#232323',
      height: 60,
      borderRadius: '28px 28px 0 0',
    },
    [theme.breakpoints.up('md')]: {
      '&::before': {
        borderRadius: '60px 60px 0 0',
      },
    },
  },
  container: {
    position: 'relative',
    width: '100% !important',
    maxWidth: '1080px !important',
    paddingTop: 93,
    paddingBottom: 120,
    display: 'flex',
    flexFlow: 'column nowrap',
    margin: '0 auto',
    [theme.breakpoints.down('sm')]: {
      paddingTop: 20,
    },
  },
  title: {
    width: '100%',
    maxWidth: 900,
    margin: '0 auto 80px',
    fontFamily: `'Sharp Grotesk DB Cyr Medium 22'`,
    fontWeight: 500,
    fontSize: 44,
    color: '#fff',
    textAlign: 'left',
    [theme.breakpoints.down('sm')]: {
      fontSize: 22,
      marginBottom: 40,
      textAlign: 'center',
      margin: '0 auto 40px',
    },
  },
  item: {
    width: '100%',
    maxWidth: 900,
    margin: '0 auto 32px',
    borderBottom: `1px dashed rgba(255, 255, 255, 0.5)`,
  },
  questionBox: {
    height: 60,
    marginBottom: 32,
    display: 'flex',
    flexFlow: 'row nowrap',
    [theme.breakpoints.down('sm')]: {
      marginBottom: 0,
      height: 'auto',
    },
  },
  question: {
    flex: 1,
    height: 60,
    lineHeight: '60px',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    fontFamily: `'Sharp Grotesk DB Cyr Medium 22'`,
    fontWeight: 500,
    fontSize: 18,
    color: '#fff',
    [theme.breakpoints.down('sm')]: {
      fontSize: 16,
      marginBottom: 24,
      lineHeight: '22.4px',
      height: 'auto',
    },
  },
  answer: {
    lineHeight: '32px',
    fontFamily: `'Inter'`,
    fontWeight: 400,
    fontSize: 20,
    color: 'rgba(255, 255, 255, 0.8)',
    paddingBottom: '32px',
    [theme.breakpoints.down('sm')]: {
      fontSize: 15,
      paddingBottom: '24px',
    },
  },
  btn: {
    display: 'inline-block',
    width: 160,
    height: 60,
    lineHeight: '60px',
    textAlign: 'center',
    background: 'transparent',
    borderRadius: '30px',
    color: '#fff',
    cursor: 'pointer',
    border: '1px solid #fff',
    transition: 'all 0.3s',
    '&:hover': {
      background: '#fff',
      color: '#171717',
      border: '1px solid #fff',
    },
  },
  btnActive: {
    background: '#fff',
    color: '#171717',
    border: '1px solid #fff',
  },
}));
