import { makeStyles, Theme } from '@material-ui/core';

export const useTopBlockStyles = makeStyles<Theme>(theme => ({
  pageRoot: {
    width: '100% !important',
    margin: 0,
    minHeight: '90vh',
    display: 'flex',
    flexFlow: 'column nowrap',
    overflow: 'hidden',
    position: 'relative',
    background: `url('/images/tokenAndNftAuction/bg.svg') no-repeat top center / 100% auto`,
    [theme.breakpoints.down('md')]: {
      background: `url('/images/tokenAndNftAuction/bg.svg') no-repeat top center / auto 100%`,
    },
  },
  pageContainer: {
    position: 'relative',
    paddingTop: 190,
    width: '100vw !important',
    maxWidth: '1110px !important',
    display: 'flex',
    margin: '0 auto 0',
    flexDirection: 'column',
    flexWrap: 'nowrap',
    justifyContent: 'center',
  },
  title1: {
    fontFamily: `'Sharp Grotesk DB Cyr Medium 22'`,
    fontWeight: 500,
    fontSize: 28,
    color: '#2B51DA',
    textAlign: 'left',
    marginBottom: 16,
    zIndex: 1,
    [theme.breakpoints.down('sm')]: {
      fontSize: 18,
      textAlign: 'center',
    },
  },
  title2: {
    fontFamily: `'Sharp Grotesk DB Cyr Medium 22'`,
    fontWeight: 500,
    fontSize: 58,
    lineHeight: '75px',
    color: '#171717',
    textAlign: 'left',
    marginBottom: 16,
    zIndex: 1,
    [theme.breakpoints.down('sm')]: {
      fontSize: 32,
      lineHeight: '41.6px',
      textAlign: 'center',
      marginBottom: 0,
    },
  },
  text: {
    fontFamily: `'Inter'`,
    fontWeight: 400,
    fontSize: 20,
    lineHeight: '32px',
    color: '#171717',
    textAlign: 'left',
    maxWidth: 970,
    margin: '40px 0 32px',
    zIndex: 1,
    [theme.breakpoints.down('sm')]: {
      fontSize: 15,
    },
  },
  btnBox: {
    display: 'flex',
    justifyContent: 'flex-start',
    marginBottom: 183,
    zIndex: 1,
    [theme.breakpoints.down('sm')]: {
      justifyContent: 'center',
      marginBottom: 80,
    },
  },
  rightImgBox: {
    position: 'relative',
    width: '100%',
    paddingTop: '80px',
    [theme.breakpoints.down('sm')]: {
      justifyContent: 'center',
    },
  },
  p1: {
    width: '100%',
    maxWidth: '441px',
  },
  p2: {
    position: 'absolute',
    left: '-20px',
    top: 90,
    width: 204,
    zIndex: 5,
    animationDelay: '2.4s',
    transform: 'translate3D(0, 0, 0)',
  },
  p2Show: {
    animation: `$floatAnimation 2s linear infinite`,
  },
  p3: {
    position: 'absolute',
    left: 120,
    top: 149,
    width: 136,
    height: 210,
    zIndex: 2,
    animationDelay: '0.7s',
    transform: 'translate3D(0, 0, 0)',
  },
  p3Show: {
    animation: `$floatAnimation 2s linear infinite`,
  },
  p4: {
    position: 'absolute',
    left: 124,
    top: '-30px',
    width: 244,
    zIndex: 3,
    animationDelay: '1s',
    transform: 'translate3D(0, 0, 0)',
    transition: 'all 0.6s',
  },
  p4Show: {
    animation: `$floatAnimation 2s linear infinite`,
  },
  bannerImg: {
    display: 'block',
    width: '100%',
  },
  text2: {
    fontFamily: `'Sharp Grotesk DB Cyr Medium 22'`,
    fontWeight: 500,
    fontSize: 36,
    lineHeight: '47px',
    color: '#171717',
    textAlign: 'left',
    zIndex: 1,
    marginBottom: 40,
    [theme.breakpoints.down('sm')]: {
      fontSize: 24,
      lineHeight: '31.2px',
      marginBottom: 24,
    },
  },
  text3: {
    fontFamily: `'Inter'`,
    fontWeight: 400,
    fontSize: 16,
    lineHeight: '24px',
    color: '#000000',
    textAlign: 'left',
    marginBottom: 16,
    zIndex: 1,
  },
  p5: {
    width: '100%',
    maxWidth: 454,
  },
  rightTitle: {
    fontFamily: `'Sharp Grotesk DB Cyr Medium 22'`,
    fontWeight: 500,
    fontSize: 32,
    lineHeight: '47px',
    color: '#171717',
    letterSpacing: 0,
    marginBottom: '40px',
    [theme.breakpoints.down('sm')]: {
      fontSize: 24,
      lineHeight: '31.2px',
      marginBottom: '24px',
    },
  },
  rightDesc: {
    fontFamily: `'Inter'`,
    fontWeight: 400,
    fontSize: 16,
    lineHeight: '24px',
    color: '#171717',
    marginBottom: 66,
    [theme.breakpoints.down('sm')]: {
      marginBottom: 40,
    },
  },
  p6: {
    width: '100%',
  },
  leftImgAnimation: {
    position: 'relative',
    height: 560,
    width: '100%',
  },
  animationImg: {
    display: 'block',
    width: '100%',
  },
  beginnerRightImgbg: {
    position: 'absolute',
    right: 0,
    top: 0,
    height: 560,
    width: 1000,
    background: '#2B51DA',
    borderRadius: 280,
  },
  p7: {
    position: 'absolute',
    left: 0,
    top: 118,
    width: 400,
    height: 318,
  },
  smallStart: {
    position: 'absolute',
    right: 141,
    top: 118,
    width: 30,
    height: 36,
  },
  bigStart: {
    position: 'absolute',
    left: 20,
    bottom: 81,
    width: 41,
    height: 50,
  },
  icon1: {
    position: 'absolute',
    bottom: 100,
    left: 150,
    width: 64,
    height: 64,
  },
  icon2: {
    position: 'absolute',
    bottom: 100,
    left: 210,
    width: 64,
    height: 64,
  },
  icon3: {
    position: 'absolute',
    bottom: 97,
    left: 265,
    width: 70,
    height: 70,
  },
  '@keyframes startAnimation': {
    '0%': {
      transform: 'scale(0.88)',
    },
    '50%': {
      transform: 'scale(1)',
    },
    '100%': {
      transform: 'scale(0.88)',
    },
  },
  '@keyframes floatAnimation': {
    '25%': {
      transform: 'translateY(5%)',
    },
    '50%, 100%': {
      transform: 'translateY(0)',
    },
    '75%': {
      transform: 'translateY(-5%)',
    },
  },
  '@keyframes scaleAnimation': {
    '25%': {
      transform: 'translateX(-50%) scale(0.9)',
    },
    '50%, 100%': {
      transform: 'translateX(-50%) scale(1)',
    },
    '75%': {
      transform: 'translateX(-50%) scale(0.9)',
    },
  },
  '@keyframes iconToRight': {
    '25%': {
      transform: 'translateX(0)',
    },
    '50%, 100%': {
      transform: 'translateX(80%)',
      zIndex: 2,
    },
    '75%': {
      transform: 'translateX(0)',
    },
  },
  '@keyframes iconToLeft': {
    '25%': {
      transform: 'translateX(0)',
    },
    '50%, 100%': {
      transform: 'translateX(-80%)',
      zIndex: 2,
    },
    '75%': {
      transform: 'translateX(0)',
    },
  },
  starAction: {
    animation: `$startAnimation 2s linear infinite`,
    [theme.breakpoints.down('md')]: {
      animation: `$startAnimation 2s linear infinite`,
    },
  },
  sdkAniBlock: {
    position: 'relative',
    width: '100%',
    maxWidth: 402,
    margin: '0 auto',
    cursor: `url('/images/home/typesOfAuction/cursor.png'),auto`,
    [theme.breakpoints.down('md')]: {
      maxWidth: '100%',
    },
  },
  sdkAniBlockCenter: {
    width: 308,
    height: 382,
    padding: '32px 0 37px',
    background: '#FFFFFF',
    boxShadow: `0px 0px 20px 1px rgba(0, 0, 0, 0.15)`,
    borderRadius: 32,
    margin: '0 auto',
    [theme.breakpoints.down('md')]: {
      width: 215,
      height: 267,
      padding: '22px 0 22px',
    },
  },
  sdkTitle: {
    fontFamily: `'Inter'`,
    fontWeight: 600,
    fontSize: 16,
    textAlign: 'center',
    lineHeight: '24px',
    marginBottom: 30,
    [theme.breakpoints.down('md')]: {
      fontSize: 11,
      marginBottom: 20,
    },
  },
  sdkBtnBox: {
    position: 'relative',
    width: '100%',
    height: 62,
    display: 'flex',
    padding: '0 20px',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 30,
    '&::before': {
      content: `''`,
      display: 'block',
      width: 66,
      height: 2,
      background: '#000',
    },
    '&::after': {
      content: `''`,
      display: 'block',
      width: 66,
      height: 2,
      background: '#000',
    },
    [theme.breakpoints.down('md')]: {
      height: 43,
      padding: '0 14px',
      '&::before': {
        content: `''`,
        display: 'block',
        width: 44,
        height: 2,
        background: '#000',
      },
      '&::after': {
        content: `''`,
        display: 'block',
        width: 44,
        height: 2,
        background: '#000',
      },
    },
  },
  icon4: {
    position: 'absolute',
    top: 0,
    left: '47%',
    width: 64,
    transform: 'translateX(-80%)',
    zIndex: 1,
    animation: '$iconToLeft 4s linear infinite',
    [theme.breakpoints.down('md')]: {
      width: 43,
      height: 43,
    },
  },
  icon5: {
    position: 'absolute',
    top: 0,
    right: '47%',
    width: 64,
    transform: 'translateX(80%)',
    zIndex: 2,
    animation: '$iconToRight 4s linear infinite',
    [theme.breakpoints.down('md')]: {
      width: 43,
      height: 43,
    },
  },
  sdkImg: {
    display: 'block',
    width: 226,
    margin: '0 auto',
    [theme.breakpoints.down('md')]: {
      width: 158,
      height: 114,
    },
  },
  sdkBlueBtn: {
    position: 'absolute',
    bottom: 64,
    left: '50%',
    width: '100%',
    maxWidth: 402,
    height: 64,
    lineHeight: '64px',
    background: '#2B51DA',
    borderRadius: 100,
    fontFamily: `'Sharp Grotesk DB Cyr Medium 22'`,
    fontWeight: 500,
    fontSize: '18px',
    color: '#fff',
    transform: 'translateX(-50%) scale(1)',
    transition: 'all 0.6s',
    textAlign: 'center',
    animation: `$scaleAnimation 4s linear infinite`,
    [theme.breakpoints.down('md')]: {
      bottom: 44,
      maxWidth: 281,
      height: 48,
      lineHeight: '48px',
      fontSize: 12,
    },
  },
}));
