import { makeStyles, Theme } from '@material-ui/core';
import { FONTS } from 'src/modules/theme/mainTheme';

export const useIntegrationStyles = makeStyles<Theme>(theme => ({
  root: {
    display: 'flex',
    flexDirection: 'column',
  },
  list: {
    position: 'relative',
    margin: '0 auto',
    width: '100%',
    display: 'flex',
    flexFlow: 'row wrap',
    justifyContent: 'flex-end',
  },
  item: {
    position: 'relative',
    width: 'calc((100% - 46px) / 2)',
    height: '69px',
    margin: '0 23px 23px 0',
    fontFamily: 'Raleway',
    fontSize: '16px',
    lineHeight: '20px',
    textAlign: 'center',
    fontWeight: 600,
    color: '#000'
  },
  arrow1: {
    position: 'absolute',
    left: 'calc((100% - 46px) / 2)',
    top: '34.5px',
    width: 20,
    height: 2,
    background: 'rgba(255, 255, 255, 0.5)',
    borderRadius: 50,
    '& img': {
      position: 'absolute',
      left: 12,
      top: -5,
      width: 12,
      height: 12,
      transform: 'rotateZ(-90deg)',
    },
  },
  arrow2: {
    position: 'absolute',
    left: '50%',
    top: '69px',
    marginLeft: 'calc((100% - 46px) / 4)',
    width: 2,
    height: 20,
    background: 'rgba(255, 255, 255, 0.5)',
    borderRadius: 50,
    '& img': {
      position: 'absolute',
      left: -5,
      top: 12,
      width: 12,
      height: 12,
    },
  },
  arrow3: {
    position: 'absolute',
    left: 'calc((100% - 46px) / 2)',
    top: 'calc(34.5px + 69px + 24px)',
    width: 20,
    height: 2,
    background: 'rgba(255, 255, 255, 0.5)',
    borderRadius: 50,
    transform: 'rotateZ(180deg)',
    '& img': {
      position: 'absolute',
      left: 12,
      top: -5,
      width: 12,
      height: 12,
      transform: 'rotateZ(-90deg)',
    },
  },
  arrow4: {
    position: 'absolute',
    left: 'calc((100% - 46px) / 4)',
    top: 'calc(69px + 69px + 24px)',
    width: 2,
    height: 20,
    background: 'rgba(255, 255, 255, 0.5)',
    borderRadius: 50,
    '& img': {
      position: 'absolute',
      left: -5,
      top: 12,
      width: 12,
      height: 12,
    },
  },
  arrow5: {
    position: 'absolute',
    left: 'calc((100% - 46px) / 2)',
    top: 'calc(69px * 2 + 34.5px + 48px)',
    width: 20,
    height: 2,
    background: 'rgba(255, 255, 255, 0.5)',
    borderRadius: 50,
    '& img': {
      position: 'absolute',
      left: 12,
      top: -5,
      width: 12,
      height: 12,
      transform: 'rotateZ(-90deg)',
    },
  },
  arrow6: {
    position: 'absolute',
    left: '50%',
    top: 'calc(69px * 3 + 48px)',
    marginLeft: 'calc((100% - 46px) / 4)',
    width: 2,
    height: 20,
    background: 'rgba(255, 255, 255, 0.5)',
    borderRadius: 50,
    '& img': {
      position: 'absolute',
      left: -5,
      top: 12,
      width: 12,
      height: 12,
    },
  },
  btnWrap: {
    display: 'flex',
    justifyContent: 'center',
    marginTop: theme.spacing(9),
  },
  btn: {
    padding: theme.spacing(4.5, 5.5),
    borderRadius: 48,
    fontFamily: FONTS.medium,
    fontWeight: 500,
    fontSize: 28,
    lineHeight: '20px',
    color: '#232323',
  },
}));
