import { makeStyles, Theme } from '@material-ui/core';

export const useTalentsBannerStyles = makeStyles<Theme>(theme => ({
  root: {
    minHeight: '90vh',
    paddingBottom: theme.spacing(15),
    display: 'flex',
    alignItems: 'flex-end',
    overflow: 'hidden',
    position: 'relative',
    top: 100,
    [theme.breakpoints.up('md')]: {
      minHeight: 'calc(100vh - 100px)',
      boxSizing: 'content-box',
      alignItems: 'center',
    },
    [theme.breakpoints.down('md')]: {
      minHeight: 'auto',
      paddingBottom: 0,
      alignItems: 'flex-start',
    },
  },
  bg: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    width: '100%',
    height: '100%',
    minWidth: '100vw',
    minHeight: '100vh',
    objectFit: 'cover',
    transform: 'translate(-50%, -50%)',
  },
  bannerMobile: {
    width: '100%',
    display: 'none',
    [theme.breakpoints.down('md')]: {
      display: 'block',
    },
  },
  container: {},
  containerBox: {
    position: 'relative',
    width: '100%',
    height: '100%',
    minHeight: '100vh',
    display: 'flex',
    flexFlow: 'row nowrap',
    justifyContent: 'flex-start',
    [theme.breakpoints.down('md')]: {
      minHeight: 'unset',
      flexFlow: 'column nowrap',
      marginBottom: '40px',
    },
  },
  leftContent: {
    width: '60%',
    display: 'flex',
    flexFlow: 'column nowrap',
    justifyContent: 'center',
    [theme.breakpoints.down('md')]: {
      width: '100%',
    },
  },
  bottomContent: {
    width: '100%',
  },
  bottomCardBlock: {
    position: 'relative',
    width: '100%',
    paddingTop: '50%',
    display: 'none',
    [theme.breakpoints.down('md')]: {
      display: 'block',
    },
  },
  card1Mobile: {
    position: 'absolute',
    left: '0',
    bottom: '0',
    transform: 'translate3D(-50%, 0, 0)',
    width: '38%',
    zIndex: 1,
    opacity: 0,
    transformOrigin: '100% 0',
    transition: 'transform 1.1s 0.3s, opacity 0.5s 0.3s',
  },
  card2Mobile: {
    position: 'absolute',
    left: '50%',
    top: '50%',
    transform: 'translate3D(-50%, 0, 0)',
    width: '50%',
    zIndex: 2,
    opacity: 0,
    transformOrigin: '50% 50%',
    transition: 'transform 1.1s 0.3s, opacity 0.5s 0.3s',
  },
  card3Mobile: {
    position: 'absolute',
    right: '0',
    bottom: '0',
    transform: 'translate3D(50%, 0, 0)',
    width: '35%',
    zIndex: 3,
    opacity: 0,
    transformOrigin: '100% 0',
    transition: 'transform 1.1s 0.3s, opacity 0.5s 0.3s',
  },
  recentlyPostedImg: {
    display: 'block',
    width: '100%',
    '& $img': {
      width: '100%',
    },
    [theme.breakpoints.down('md')]: {
      display: 'none',
    },
  },
  recentlyPostedImgMobile: {
    display: 'none',
    width: '100%',
    '& $img': {
      width: '100%',
    },
    [theme.breakpoints.down('md')]: {
      display: 'block',
    },
  },
  rightContent: {
    position: 'relative',
    flex: 1,
    [theme.breakpoints.down('md')]: {
      display: 'none',
    },
  },
  card1: {
    position: 'absolute',
    left: '60px',
    top: '50%',
    transform: 'translate3D(0, 0, 0)',
    width: '422px',
    zIndex: 3,
    opacity: 0,
    marginTop: '100px',
    marginLeft: '-20px',
    transformOrigin: '100% 0',
    transition: 'transform 1.1s 0.3s, opacity 0.5s 0.3s',
  },
  card2: {
    position: 'absolute',
    left: '60px',
    top: '50%',
    transform: 'translate3D(0, 0, 0)',
    width: '402px',
    zIndex: 2,
    opacity: 0,
    marginTop: '0px',
    transformOrigin: '100% 0',
    transition: 'transform 0.8s 0.3s, opacity 0.5s 0.3s',
  },
  card3: {
    position: 'absolute',
    left: '60px',
    top: '50%',
    transform: 'translate3D(0, 0, 0)',
    width: '412px',
    zIndex: 1,
    opacity: 0,
    marginTop: '-100px',
    transformOrigin: '100% 0',
    transition: 'transform 0.5s 0.3s, opacity 0.5s 0.3s',
  },
  title: {
    lineHeight: '70px',
    color: '#480CDB',
    fontSize: '26px',
    [theme.breakpoints.down('md')]: {
      fontSize: '16px',
      lineHeight: '36px',
    },
  },
  description: {
    paddingLeft: '57px',
    textIndent: '-114px',
    marginBottom: theme.spacing(3.5),
    width: '100%',
    maxWidth: '650px',
    lineHeight: '70px',
    textAlign: 'center',
    color: '#171717',
    [theme.breakpoints.down('md')]: {
      width: '100%',
      paddingLeft: '0',
      maxWidth: '100%',
      textIndent: '0',
      textAlign: 'left',
      fontSize: '38px',
      lineHeight: '55px',
      marginBottom: '12px',
    },
  },
  description1: {
    textIndent: '0',
    width: '100%',
    lineHeight: '70px',
    textAlign: 'left',
    color: '#171717',
    fontSize: '48px',
  },
  description2: {
    marginBottom: theme.spacing(3.5),
    width: '100%',
    lineHeight: '70px',
    textIndent: '40px',
    textAlign: 'left',
    color: '#171717',
    fontSize: '48px',
  },
  detail: {
    marginBottom: theme.spacing(8.5),
    maxWidth: 570,
    lineHeight: '26px',
    color: 'rgba(0, 0, 0, 0.8)',
    [theme.breakpoints.down('md')]: {
      fontSize: '16px',
      marginBottom: '48px',
    },
  },
  recentlyPostedJobs: {
    fontFamily: 'Sharp Grotesk DB Cyr Medium 22',
    marginBottom: '20px',
    width: '100%',
    fontSize: '32px',
    lineHeight: '60px',
    textAlign: 'left',
    color: '#232323',
    [theme.breakpoints.down('md')]: {
      width: '100%',
      fontSize: '20px',
      lineHeight: '36px',
    },
  },
  'sign-up-btn': {
    marginRight: theme.spacing(2),
    height: 60,
    lineHeight: '20px',
    background: '#2B51DA',
    borderRadius: '30px',
    fontSize: '16px',
    color: '#fff',
    '& .MuiButton-label': {
      padding: theme.spacing(0, 4),
    },
    '&:before': {
      background: '#2B51DA',
    },
    '&:hover': {
      background:
        'linear-gradient(90deg, rgba(255, 255, 255, 0) 40.91%, rgba(255, 255, 255, 0.24) 76.36%, rgba(255, 255, 255, 0.12) 100%), #480CDB',
    },
    [theme.breakpoints.down('md')]: {
      width: '100%',
      marginBottom: '20px',
      marginRight: '0',
    },
  },
  'post-job-btn': {
    height: 60,
    lineHeight: '20px',
    background: '#fff',
    border: '1px solid #2B51DA',
    borderRadius: '30px',
    fontSize: '16px',
    color: '#2B51DA',
    '& .MuiButton-label': {
      padding: theme.spacing(0, 5.5),
    },
    '&:hover': {
      background: '#2B51DA',
      color: '#fff',
    },
    [theme.breakpoints.down('md')]: {
      width: '100%',
      marginBottom: '48px',
      marginRight: '0',
    },
  },
  rightContentInView: {
    '& $card1': {
      opacity: 1,
      transform: 'translate3D(0, -50%, 0)',
    },
    '& $card2': {
      opacity: 1,
      transform: 'translate3D(0, -50%, 0)',
    },
    '& $card3': {
      opacity: 1,
      transform: 'translate3D(0, -50%, 0)',
    },
    '& $card1Mobile': {
      opacity: 1,
      transform: 'translate3D(0, 0, 0)',
    },
    '& $card2Mobile': {
      opacity: 1,
      transform: 'translate3D(-50%, -60%, 0)',
    },
    '& $card3Mobile': {
      opacity: 1,
      transform: 'translate3D(0, 0, 0)',
    },
  },
}));
