import { makeStyles, Theme } from '@material-ui/core';

export const useTypesOfAuctionBounceStyles = makeStyles<Theme>(theme => ({
  root: {
    position: 'relative',
    backgroundColor: '#232323',
    minHeight: '100vh',
    pointerEvents: 'auto',
    '&::before': {
      content: `''`,
      display: 'block',
      position: 'absolute',
      top: -54,
      width: '100%',
      background: '#232323',
      height: 60,
      borderRadius: '28px 28px 0 0',
    },
    [theme.breakpoints.up('md')]: {
      '&::before': {
        borderRadius: '60px 60px 0 0',
      },
    },
  },
  container: {
    position: 'relative',
    width: '100% !important',
    maxWidth: '1110px !important',
    paddingTop: 20,
    paddingBottom: 120,
    display: 'flex',
    flexFlow: 'column nowrap',
    margin: '0 auto',
    [theme.breakpoints.down('sm')]: {
      paddingTop: 20,
    },
  },
  title: {
    fontFamily: `'Sharp Grotesk DB Cyr Medium 22'`,
    fontWeight: 500,
    fontSize: 44,
    color: '#fff',
    textAlign: 'left',
    marginBottom: 30,
    [theme.breakpoints.down('sm')]: {
      fontSize: 22,
      marginBottom: 40,
      textAlign: 'center',
    },
  },
  item: {
    width: '100%',
    height: 'max-content',
    borderRadius: 20,
    padding: '28px 0 0',
    display: 'flex',
    flexFlow: 'row nowrap',
    [theme.breakpoints.down('sm')]: {
      flexFlow: 'column',
      alignItems: 'center',
      height: 'auto',
      padding: '24px 0px 0',
    },
    cursor: 'pointer',
  },
  itemLeft: {
    width: 109,
    display: 'flex',
    flexFlow: 'column nowrap',
    justifyContent: 'center',
    alignItems: 'center',
  },
  itemImg: {
    width: 40,
    height: 40,
    [theme.breakpoints.down('sm')]: {
      marginBottom: '21px',
    },
  },
  itemRight: {
    flex: 1,
    display: 'flex',
    flexFlow: 'column nowrap',
    justifyContent: 'center',
    padding: '0 33px 0',
    // height: 175,
    [theme.breakpoints.down('sm')]: {
      borderLeft: '0px',
      paddingTop: '24px',
    },
  },
  itemTitle: {
    fontFamily: `'Sharp Grotesk DB Cyr Medium 22'`,
    fontWeight: 500,
    fontSize: 16,
    color: '#fff',
    marginBottom: 18,
    textAlign: 'left',
    [theme.breakpoints.down('sm')]: {
      textAlign: 'center',
    },
    lineHeight: '20px',
  },
  itemDesc: {
    fontFamily: `'Inter'`,
    fontWeight: 400,
    fontSize: 14,
    color: '#fff',
    lineHeight: '21px',
    textAlign: 'left',
    [theme.breakpoints.down('sm')]: {
      textAlign: 'center',
    },
    opacity: 0.8,
  },
  animationBlock: {
    width: '100%',
    maxWidth: '1110px',
    margin: '0 auto',
    display: 'flex',
    flexFlow: 'row nowrap',
    justifyContent: 'center',
    alignItems: 'center',
  },
  centerTop: {
    width: '100%',
    display: 'flex',
    flexFlow: 'row nowrap',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  animationBlockLeft: {
    width: 270,
    display: 'flex',
    flexFlow: 'column nowrap',
    justifyContent: 'flex-start',
    alignItems: 'center',
    padding: ' 27px 20px',
    border: `2px solid rgba(255, 255, 255, 0.5)`,
    borderRadius: '20px',
    cursor: `url('/images/home/typesOfAuction/cursor.png'),auto`,
  },
  animationBlockCenter: {
    flex: 1,
    display: 'flex',
    flexFlow: 'column nowrap',
    justifyContent: 'flex-start',
    alignItems: 'center',
    cursor: `url('/images/home/typesOfAuction/cursor.png'),auto`,
  },
  centerBottom: {
    width: 'calc(100% - 40px)',
    margin: '0 auto',
    display: 'flex',
    flexFlow: 'row nowrap',
    justifyContent: 'center',
    alignItems: 'center',
    padding: ' 5px 0',
    border: `2px solid rgba(255, 255, 255, 0.5)`,
    borderRadius: '20px',
    marginTop: '5px',
  },
  p2: {
    zIndex:2,
    position:'fixed',
    width: '50%',
    right: 0,
    top:'50%',
    transform: 'translate3D(550px, -30%, 0)',
    opacity: 0,
    [theme.breakpoints.down('sm')]: {
      width: '120px',
      top: '100px',
      right: -20,
      position:'relative',
      transform: 'translate3D(0, -30%, 0)',
    },
    transition: 'all 0.4s',
  },
  p2Show: {
    opacity: 1,
   transform: 'translate3D(0, -30%, 0)',
    [theme.breakpoints.down('sm')]: {
      transform: 'translate3D(0, -30%, 0)',
    },
  },
  animationImg: {
    width: '100%',
  },
  svg: {
    width: '100%',
  },
}));
