import { makeStyles } from '@material-ui/core';
import { PALETTE } from 'src/modules/theme/mainTheme';

export const useBounceNFTBlockstyles = makeStyles(theme => ({
  root: {
    position: 'relative',
    boxSizing: 'border-box',
    background: '#FFFFFF',
    color: '#171717',
    // minHeight: '100vh',
    paddingTop: 60,
    pointerEvents: 'auto',
    '&::before': {
      content: `''`,
      display: 'block',
      position: 'absolute',
      top: -59,
      width: '100%',
      background: '#FFFFFF',
      height: 60,
      borderRadius: '28px 28px 0 0',
    },
    [theme.breakpoints.up('md')]: {
      '&::before': {
        borderRadius: '60px 60px 0 0',
      },
    },
    [theme.breakpoints.down('md')]: {
      paddingBottom: theme.spacing(14),
    },
    '& ::selection': {
      background: PALETTE.background.default,
      color: PALETTE.text.reverse,
    },
  },
  wrap: {
    position: 'relative',
    overflow: 'hidden',
    paddingBottom: '90px',
  },
  container: {
    // paddingRight: 0,
  },
  title: {
    textAlign: 'center',
    fontSize: '48px',
    lineHeight: '50px',
    [theme.breakpoints.down('md')]: {
      fontSize: '24px',
      lineHeight: '36px',
    },
  },
  subtitle: {
    color: 'rgba(23, 23, 23, 0.8)',
    textAlign: 'center',
    margin: '20px auto 0',
    width: '70%',
    fontSize: '16px',
    lineHeight: '24px',
    [theme.breakpoints.down('md')]: {
      fontSize: '16px',
      lineHeight: '36px',
      width: '100%',
    },
  },
  smallTitle: {
    fontSize: 40,
    [theme.breakpoints.down('md')]: {
      fontSize: '24px',
      lineHeight: '36px',
      width: '100%',
    },
  },
  cardBox: {
    position: 'relative',
    width: '100%',
    overflowX: 'auto',
    overflowY: 'hidden',
  },
  cardItem: {
    position: 'relative',
    display: 'block',
    width: '100%',
    minWidth: '1000px',
    paddingTop: '140px',
    [theme.breakpoints.down('md')]: {
      paddingTop: '137px',
    },
  },
  cardBoxBg: {
    display: 'block',
    width: '100%',
    minWidth: '1000px',
  },
  card1: {
    position: 'absolute',
    width: '355px',
    bottom: '24px',
    left: '50%',
    transform: 'translate3D(-50%, 50%, 0)',
    marginLeft: '-255px',
    zIndex: 4,
    opacity: 0,
    transformOrigin: '100% 0',
    transition: 'transform 0.5s 0.3s, opacity 0.5s 0.3s',
  },
  card2: {
    position: 'absolute',
    width: '315px',
    bottom: '104px',
    left: '50%',
    transform: 'translate3D(-50%, 50%, 0)',
    marginLeft: '-145px',
    zIndex: 3,
    opacity: 0,
    transformOrigin: '100% 0',
    transition: 'transform 0.8s 0.3s, opacity 0.5s 0.3s',
  },
  card3: {
    position: 'absolute',
    width: '274px',
    bottom: '130px',
    left: '50%',
    transform: 'translate3D(-50%, 50%, 0)',
    marginLeft: '45px',
    zIndex: 2,
    opacity: 0,
    transformOrigin: '100% 0',
    transition: 'transform 1.1s 0.3s, opacity 0.5s 0.3s',
  },
  card4: {
    position: 'absolute',
    width: '355px',
    bottom: '24px',
    left: '50%',
    transform: 'translate3D(-50%, 50%, 0)',
    marginLeft: '255px',
    zIndex: 1,
    opacity: 0,
    transformOrigin: '100% 0',
    transition: 'transform 1.4s 0.3s, opacity 0.5s 0.3s',
  },
  cardText: {
    fontFamily: 'Sharp Grotesk DB Cyr Medium 22',
    fontWeight: 500,
    fontSize: '24px',
    lineHeight: '31px',
    color: '#FFFFFF',
    position: 'absolute',
    width: '100%',
    bottom: '55px',
    left: '0',
    textAlign: 'center',
    opacity: 0,
    transform: 'translate3D(0, -50%, 0)',
    transformOrigin: '100% 0',
    transition: 'transform 0.5s 0.3s, opacity 0.5s 0.3s',
    [theme.breakpoints.down('md')]: {
      fontSize: '16px',
      lineHeight: '24px',
    },
  },
  cardBoxInView: {
    '& $card1': {
      opacity: 1,
      transform: 'translate3D(-50%, 0, 0)',
    },
    '& $card2': {
      opacity: 1,
      transform: 'translate3D(-50%, 0, 0)',
    },
    '& $card3': {
      opacity: 1,
      transform: 'translate3D(-50%, 0, 0)',
    },
    '& $card4': {
      opacity: 1,
      transform: 'translate3D(-50%, 0, 0)',
    },
    '& $cardText': {
      opacity: 1,
      transform: 'translate3D(0, 0, 0)',
    },
  },
}));
